### PR TITLE
Nicer Readme

### PR DESCRIPTION
**Pull request by inson1**
@Andrewerr idk what is 🪞?

### CODE REVIEW

**Comment by Andrewerr** [comment]
🪞 is a mirror emoji

**Comment by inson1** [comment]
@Andrewerr i didnt know that, thanks :)

**Review by Andrewerr — COMMENTED** [review]
Thankyou for your changes! I like how new README looks
But why have you removed F-Droid version badge?

**Comment by inson1** [comment]
@Andrewerr oh, I didnt notice it, miss delete

**Review by Andrewerr — APPROVED** [review]
Ok, everything looks great, so I am merging this PR

**Pull request merged**
